const api_data = [
    {
      name: "KFC",
      cuisine: "American, Chicken, Burger",
      rating: "4.5",
      eta: "24 minutes",
      costfortwo: "10£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,w_1317,h_480/f_auto/q_auto/dpr_2.0/d_uk:cuisines:chicken-8.jpg/v1/uk/restaurants/74058.jpg",
    },
    {
      name: "Hyderabad Darbar",
      cuisine: "Chicken, American",
      rating: "4.7",
      eta: "45 minutes",
      costfortwo: "18£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,w_1317,h_480/f_auto/q_auto/dpr_2.0/d_uk:cuisines:indian-2.jpg/v1/uk/restaurants/101692.jpg",
    },
    {
      name: "Papa's Chicken",
      cuisine: "American, Chicken, Peri peri",
      rating: "4.2",
      eta: "20 minutes",
      costfortwo: "12£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,w_1317,h_480/f_auto/q_auto/dpr_2.0/d_uk:cuisines:chicken-3.jpg/v1/uk/restaurants/254383.jpg",
    },
    {
      name: "Shinde's Pure veg",
      cuisine: "Indian, Vegetarian",
      rating: "3.9",
      eta: "15 minutes",
      costfortwo: "16£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_240/f_auto/q_auto/dpr_2.0/d_uk:cuisines:indian-8.jpg/v1/uk/restaurants/75618.jpg",
    },
    {
      name: "Vasantha Villas",
      cuisine: "Indian, Vegetarian",
      rating: "3.7",
      eta: "40 minutes",
      costfortwo: "20£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_240/f_auto/q_auto/dpr_2.0/d_uk:cuisines:vegetarian-2.jpg/v1/uk/restaurants/103272.jpg",
    },{
      name: "German Doner Kebab",
      cuisine: "Kebab, Halal",
      rating: "3.9",
      eta: "10-15 minutes",
      costfortwo: "16£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_136,w_288/f_auto/q_auto/dpr_2.0/d_uk:cuisines:kebabs-9.jpg/v1/uk/restaurants/113669.jpg",
    },{
      name: "Banjos",
      cuisine: "Chicken, Pizza, Halal",
      rating: "2.8",
      eta: "40-45 minutes",
      costfortwo: "12£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_240/f_auto/q_auto/dpr_2.0/d_uk:cuisines:chicken-3.jpg/v1/uk/restaurants/253743.jpg",
    },
    {
      name: "KFC",
      cuisine: "American, Chicken, Burger",
      rating: "4.5",
      eta: "24 minutes",
      costfortwo: "10£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,w_1317,h_480/f_auto/q_auto/dpr_2.0/d_uk:cuisines:chicken-8.jpg/v1/uk/restaurants/74058.jpg",
    },
    {
      name: "Hyderabad Darbar",
      cuisine: "Chicken, American",
      rating: "4.7",
      eta: "45 minutes",
      costfortwo: "18£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,w_1317,h_480/f_auto/q_auto/dpr_2.0/d_uk:cuisines:indian-2.jpg/v1/uk/restaurants/101692.jpg",
    },
    {
      name: "Papa's Chicken",
      cuisine: "American, Chicken, Peri peri",
      rating: "4.2",
      eta: "20 minutes",
      costfortwo: "12£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,w_1317,h_480/f_auto/q_auto/dpr_2.0/d_uk:cuisines:chicken-3.jpg/v1/uk/restaurants/254383.jpg",
    },
    {
      name: "Shinde's Pure veg",
      cuisine: "Indian, Vegetarian",
      rating: "3.9",
      eta: "15 minutes",
      costfortwo: "16£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_240/f_auto/q_auto/dpr_2.0/d_uk:cuisines:indian-8.jpg/v1/uk/restaurants/75618.jpg",
    },
    {
      name: "Vasantha Villas",
      cuisine: "Indian, Vegetarian",
      rating: "3.7",
      eta: "40 minutes",
      costfortwo: "20£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_240/f_auto/q_auto/dpr_2.0/d_uk:cuisines:vegetarian-2.jpg/v1/uk/restaurants/103272.jpg",
    },{
      name: "German Doner Kebab",
      cuisine: "Kebab, Halal",
      rating: "3.9",
      eta: "10-15 minutes",
      costfortwo: "16£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_136,w_288/f_auto/q_auto/dpr_2.0/d_uk:cuisines:kebabs-9.jpg/v1/uk/restaurants/113669.jpg",
    },{
      name: "Banjos",
      cuisine: "Chicken, Pizza, Halal",
      rating: "2.8",
      eta: "40-45 minutes",
      costfortwo: "12£",
      imageSrc: "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_thumb,h_240/f_auto/q_auto/dpr_2.0/d_uk:cuisines:chicken-3.jpg/v1/uk/restaurants/253743.jpg",
    }
  ];
  export default api_data;